using MapGeneration.Distributors;
using System.Runtime.InteropServices;

namespace LockLocker;

#region Pas toucher !
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :1.0.20.132
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

partial class Code_LockerChamber : System.Dynamic.DynamicObject
{
    LockerChamber @this;
}
#endregion

